name: Node.js Firebase App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Copy .env file
        run: cp .env

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions

        env:
          APIKEY: ${{secrets.APIKEY}}
          AUTHDOMAIN: ${{secrets.AUTHDOMAIN}}
          DATABASEURL: ${{secrets.DATABASEURL}}
          PROJECTID: ${{secrets.PROJECTID}}
          STORAGEBUCKET: ${{secrets.STORAGEBUCKET}}
          MESSAGINGSENDERID: ${{secrets.MESSAGINGSENDERID}}
          APPID: ${{secrets.APPID}}
          MEASUREMENTID: ${{secrets.MEASUREMENTID}}
