name: Node.js Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Deploy to Cyclic.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CYCLIC_HOST }}
          username: ${{ secrets.CYCLIC_USERNAME }}
          password: ${{ secrets.CYCLIC_PASSWORD }}
          script: |
            cd /path/to/project
            npm install --production
            pm2 restart server
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          API_KEY: ${{ secrets.API_KEY }}
