name: Node.js Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Deploy to Cyclic.sh
        uses: appleboy/ssh-action@master
        with:         
          script: |
            cd /path/to/project
            npm install --production
            pm2 restart server
        env:
          APIKEY: ${{secrets.APIKEY}}
          AUTHDOMAIN: ${{secrets.AUTHDOMAIN}}
          DATABASEURL: ${{secrets.DATABASEURL}}
          PROJECTID: ${{secrets.PROJECTID}}
          STORAGEBUCKET: ${{secrets.STORAGEBUCKET}}
          MESSAGINGSENDERID: ${{secrets.MESSAGINGSENDERID}}
          APPID: ${{secrets.APPID}}
          MEASUREMENTID: ${{secrets.MEASUREMENTID}}
